### ISSUE TITLE
[P0] Review/validate existing dockerfile for Open Data Hub

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/text-generation-inference#2]
Ref: https://github.com/IBM/text-generation-inference/blob/main/Dockerfile

**Comment by heyselbi** [comment]
@Xaenalt could you provide here what was tested and validated?

**Comment by Xaenalt** [comment]
The builds worked locally, and we were able to perform an e2e test of the serving workflow using caikit+TGIS
