### ISSUE TITLE
Sync image with TGIS updates

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/text-generation-inference#26]
- [x] Update TGIS image
- [x] Update caikit-TGIS image

**Comment by Xaenalt** [comment]
Updated TGIS image to the latest code drop from IBM. This involved rebasing our commits on top of the latest code from IBM. Ended up having to force push this

For caikit-tgis-serving, updated to the new version and added a longer timeout to address an issue hit by IBM
